from __future__ import annotations


GO2_CONFIG = {
    "base_joint_name": "base",
    "leg_joint_names": [
        "FL_hip_joint",
        "FL_thigh_joint",
        "FL_calf_joint",
        "FR_hip_joint",
        "FR_thigh_joint",
        "FR_calf_joint",
        "RL_hip_joint",
        "RL_thigh_joint",
        "RL_calf_joint",
        "RR_hip_joint",
        "RR_thigh_joint",
        "RR_calf_joint",
    ],
    "neutral_joint_angles": {
        "FL_hip_joint": 0.1,
        "FL_thigh_joint": 0.8,
        "FL_calf_joint": -1.5,
        "FR_hip_joint": -0.1,
        "FR_thigh_joint": 0.8,
        "FR_calf_joint": -1.5,
        "RL_hip_joint": 0.1,
        "RL_thigh_joint": 1.0,
        "RL_calf_joint": -1.5,
        "RR_hip_joint": -0.1,
        "RR_thigh_joint": 1.0,
        "RR_calf_joint": -1.5,
    },
    "actuator_names": [
        "FL_hip_actuator",
        "FL_thigh_actuator",
        "FL_calf_actuator",
        "FR_hip_actuator",
        "FR_thigh_actuator",
        "FR_calf_actuator",
        "RL_hip_actuator",
        "RL_thigh_actuator",
        "RL_calf_actuator",
        "RR_hip_actuator",
        "RR_thigh_actuator",
        "RR_calf_actuator",
    ],
    "kps": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
    "kds": [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    "imu_site_name": "imu",
    "contact_site_names": ["FL_site", "FR_site", "RL_site", "RR_site"],
    "sensor_foot_touch_names": ["FL_touch", "FR_touch", "RL_touch", "RR_touch"],
    "base_contact_body_names": ["base", "FL_hip", "FR_hip", "RL_hip", "RR_hip"],
    "foot_body_names": ["FL_foot", "FR_foot", "RL_foot", "RR_foot"],
    "action_scale": [
        0.2,
        1.0,
        0.8,
        0.2,
        1.0,
        0.8,
        0.2,
        1.0,
        0.8,
        0.2,
        1.0,
        0.8,
    ],
}

