from __future__ import annotations


GO2_CONFIG = {
    "base_joint_name": "_joint_0",
    "leg_joint_names": [
        "FL_hip_joint",
        "FL_thigh_joint",
        "FL_calf_joint",
        "FR_hip_joint",
        "FR_thigh_joint",
        "FR_calf_joint",
        "RL_hip_joint",
        "RL_thigh_joint",
        "RL_calf_joint",
        "RR_hip_joint",
        "RR_thigh_joint",
        "RR_calf_joint",
    ],
    "neutral_joint_angles": {
        "FL_hip_joint": -0.1,
        "FL_thigh_joint": 0.9,
        "FL_calf_joint": -1.8,
        "FR_hip_joint": 0.1,
        "FR_thigh_joint": 0.9,
        "FR_calf_joint": -1.8,
        "RL_hip_joint": -0.1,
        "RL_thigh_joint": 0.9,
        "RL_calf_joint": -1.8,
        "RR_hip_joint": 0.1,
        "RR_thigh_joint": 0.9,
        "RR_calf_joint": -1.8,
    },
    "actuator_names": [
        "FL_hip",
        "FL_thigh",
        "FL_calf",
        "FR_hip",
        "FR_thigh",
        "FR_calf",
        "RL_hip",
        "RL_thigh",
        "RL_calf",
        "RR_hip",
        "RR_thigh",
        "RR_calf",
    ],
    "kps": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
    "kds": [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    "imu_site_name": "imu",
    "contact_site_names": [],
    "sensor_foot_touch_names": ["FL_touch", "FR_touch", "RL_touch", "RR_touch"],
    "base_contact_body_names": ["base_link", "FL_hip", "FR_hip", "RL_hip", "RR_hip"],
    "foot_body_names": ["FL_calf", "FR_calf", "RL_calf", "RR_calf"],
    "action_scale": [
        0.2,
        1.0,
        0.8,
        0.2,
        1.0,
        0.8,
        0.2,
        1.0,
        0.8,
        0.2,
        1.0,
        0.8,
    ],
}
