from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np


@dataclass(frozen=True)
class TerrainMesh:
    vertices: np.ndarray
    faces: np.ndarray

    def write_obj(self, path: str | Path) -> Path:
        output_path = Path(path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as file:
            file.write("# Generated by orca_rl terrain generator\n")
            for vertex in self.vertices:
                file.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
            for face in self.faces:
                a, b, c = face + 1
                file.write(f"f {a} {b} {c}\n")
        return output_path


@dataclass(frozen=True)
class HeightField:
    heights: np.ndarray
    resolution: float
    origin_xy: tuple[float, float]

    @property
    def size_xy(self) -> tuple[float, float]:
        rows, cols = self.heights.shape
        return ((cols - 1) * self.resolution, (rows - 1) * self.resolution)

    def height_at(self, x: float, y: float) -> float:
        col = (float(x) - self.origin_xy[0]) / self.resolution
        row = (float(y) - self.origin_xy[1]) / self.resolution
        col = float(np.clip(col, 0.0, self.heights.shape[1] - 1.001))
        row = float(np.clip(row, 0.0, self.heights.shape[0] - 1.001))

        c0 = int(np.floor(col))
        r0 = int(np.floor(row))
        c1 = min(c0 + 1, self.heights.shape[1] - 1)
        r1 = min(r0 + 1, self.heights.shape[0] - 1)
        dc = col - c0
        dr = row - r0
        h00 = self.heights[r0, c0]
        h01 = self.heights[r0, c1]
        h10 = self.heights[r1, c0]
        h11 = self.heights[r1, c1]
        return float((1.0 - dr) * ((1.0 - dc) * h00 + dc * h01) + dr * ((1.0 - dc) * h10 + dc * h11))

    def scan(
        self,
        base_xy: np.ndarray,
        yaw: float,
        *,
        size: tuple[float, float],
        resolution: float,
    ) -> np.ndarray:
        xs = np.arange(-size[0] / 2.0, size[0] / 2.0 + 0.5 * resolution, resolution)
        ys = np.arange(-size[1] / 2.0, size[1] / 2.0 + 0.5 * resolution, resolution)
        cos_yaw = float(np.cos(yaw))
        sin_yaw = float(np.sin(yaw))
        samples: list[float] = []
        for x in xs:
            for y in ys:
                world_x = float(base_xy[0]) + cos_yaw * float(x) - sin_yaw * float(y)
                world_y = float(base_xy[1]) + sin_yaw * float(x) + cos_yaw * float(y)
                samples.append(self.height_at(world_x, world_y))
        return np.asarray(samples, dtype=np.float64)

    def to_mesh(self) -> TerrainMesh:
        rows, cols = self.heights.shape
        xs = self.origin_xy[0] + np.arange(cols, dtype=np.float64) * self.resolution
        ys = self.origin_xy[1] + np.arange(rows, dtype=np.float64) * self.resolution
        grid_x, grid_y = np.meshgrid(xs, ys)
        vertices = np.stack([grid_x.reshape(-1), grid_y.reshape(-1), self.heights.reshape(-1)], axis=1)

        faces: list[tuple[int, int, int]] = []
        for row in range(rows - 1):
            for col in range(cols - 1):
                a = row * cols + col
                b = a + 1
                c = a + cols
                d = c + 1
                faces.append((a, c, b))
                faces.append((b, c, d))
        return TerrainMesh(vertices=vertices.astype(np.float64), faces=np.asarray(faces, dtype=np.int64))


def generate_height_field(terrain_cfg: dict[str, Any] | None, rng: np.random.Generator) -> HeightField:
    if not terrain_cfg or terrain_cfg.get("terrain_type", "plane") == "plane":
        return _plane_height_field()

    generator = terrain_cfg.get("terrain_generator") or {}
    tile_size = tuple(float(v) for v in generator.get("size", (8.0, 8.0)))
    resolution = float(generator.get("horizontal_scale", 0.10))
    num_rows = int(generator.get("num_rows", 1))
    num_cols = int(generator.get("num_cols", 1))
    total_x = max(tile_size[0] * num_cols, resolution)
    total_y = max(tile_size[1] * num_rows, resolution)
    cols = int(round(total_x / resolution)) + 1
    rows = int(round(total_y / resolution)) + 1
    heights = np.zeros((rows, cols), dtype=np.float64)

    sub_terrains = tuple(generator.get("sub_terrains", ())) or (
        {"name": "random_uniform", "proportion": 1.0, "params": {}},
    )
    names = [str(item.get("name", "random_uniform")) for item in sub_terrains]
    weights = np.asarray([float(item.get("proportion", 1.0)) for item in sub_terrains], dtype=np.float64)
    weights = weights / max(float(np.sum(weights)), 1e-9)

    tile_cols = max(2, int(round(tile_size[0] / resolution)) + 1)
    tile_rows = max(2, int(round(tile_size[1] / resolution)) + 1)
    for tile_row in range(num_rows):
        for tile_col in range(num_cols):
            index = int(rng.choice(len(names), p=weights))
            sub_cfg = dict(sub_terrains[index])
            tile = _generate_sub_terrain(names[index], sub_cfg.get("params", {}), tile_rows, tile_cols, resolution, rng)
            r0 = tile_row * (tile_rows - 1)
            c0 = tile_col * (tile_cols - 1)
            r1 = min(r0 + tile_rows, rows)
            c1 = min(c0 + tile_cols, cols)
            heights[r0:r1, c0:c1] = tile[: r1 - r0, : c1 - c0]

    border_width = float(generator.get("border_width", 0.0))
    if border_width > 0.0:
        border_cells = int(round(border_width / resolution))
        if border_cells > 0:
            heights[:border_cells, :] = 0.0
            heights[-border_cells:, :] = 0.0
            heights[:, :border_cells] = 0.0
            heights[:, -border_cells:] = 0.0

    return HeightField(
        heights=heights,
        resolution=resolution,
        origin_xy=(-0.5 * total_x, -0.5 * total_y),
    )


def _plane_height_field() -> HeightField:
    return HeightField(heights=np.zeros((2, 2), dtype=np.float64), resolution=1.0, origin_xy=(-0.5, -0.5))


def _generate_sub_terrain(
    name: str,
    params: dict[str, Any],
    rows: int,
    cols: int,
    resolution: float,
    rng: np.random.Generator,
) -> np.ndarray:
    if name == "pyramid_stairs":
        return _pyramid_stairs(rows, cols, resolution, params)
    if name == "discrete_obstacles":
        return _discrete_obstacles(rows, cols, resolution, params, rng)
    if name == "wave":
        return _wave(rows, cols, resolution, params, rng)
    return _random_uniform(rows, cols, params, rng)


def _random_uniform(rows: int, cols: int, params: dict[str, Any], rng: np.random.Generator) -> np.ndarray:
    low, high = params.get("height_range", (-0.04, 0.04))
    step = float(params.get("step", 0.01))
    heights = rng.uniform(float(low), float(high), size=(rows, cols))
    if step > 0.0:
        heights = np.round(heights / step) * step
    return heights


def _pyramid_stairs(rows: int, cols: int, resolution: float, params: dict[str, Any]) -> np.ndarray:
    low, high = params.get("step_height_range", (0.02, 0.10))
    step_height = 0.5 * (float(low) + float(high))
    step_width = max(float(params.get("step_width", 0.30)), resolution)
    yy, xx = np.mgrid[0:rows, 0:cols]
    center_r = 0.5 * (rows - 1)
    center_c = 0.5 * (cols - 1)
    distance = np.maximum(np.abs(yy - center_r), np.abs(xx - center_c)) * resolution
    levels = np.floor(distance / step_width)
    return -step_height * levels.astype(np.float64)


def _discrete_obstacles(
    rows: int,
    cols: int,
    resolution: float,
    params: dict[str, Any],
    rng: np.random.Generator,
) -> np.ndarray:
    low, high = params.get("height_range", (0.02, 0.10))
    num_obstacles = int(params.get("num_obstacles", 16))
    heights = np.zeros((rows, cols), dtype=np.float64)
    max_width = max(1, int(round(0.60 / resolution)))
    min_width = max(1, int(round(0.20 / resolution)))
    for _ in range(num_obstacles):
        width_r = int(rng.integers(min_width, max_width + 1))
        width_c = int(rng.integers(min_width, max_width + 1))
        r0 = int(rng.integers(0, max(1, rows - width_r)))
        c0 = int(rng.integers(0, max(1, cols - width_c)))
        heights[r0 : r0 + width_r, c0 : c0 + width_c] = rng.uniform(float(low), float(high))
    return heights


def _wave(
    rows: int,
    cols: int,
    resolution: float,
    params: dict[str, Any],
    rng: np.random.Generator,
) -> np.ndarray:
    low, high = params.get("amplitude_range", (0.02, 0.08))
    amplitude = float(rng.uniform(float(low), float(high)))
    waves = int(params.get("num_waves", 3))
    xs = np.arange(cols, dtype=np.float64) * resolution
    ys = np.arange(rows, dtype=np.float64) * resolution
    grid_x, grid_y = np.meshgrid(xs, ys)
    length_x = max(xs[-1] - xs[0], resolution)
    length_y = max(ys[-1] - ys[0], resolution)
    return amplitude * (
        np.sin(2.0 * np.pi * waves * grid_x / length_x)
        + 0.5 * np.cos(2.0 * np.pi * waves * grid_y / length_y)
    )
