## Orca G1 velocity PPO defaults.
seed: 1
num_steps_per_env: 24
max_iterations: 10001
save_interval: 100
logger: wandb
wandb_project: orcalab-rslrl
experiment_name: g1_velocity
run_name: orca
check_for_nan: false
obs_groups:
  actor: [actor]
  critic: [critic]
algorithm:
  class_name: PPO
  learning_rate: 0.001
  num_learning_epochs: 5
  num_mini_batches: 4
  schedule: adaptive
  value_loss_coef: 1.0
  clip_param: 0.2
  use_clipped_value_loss: true
  desired_kl: 0.01
  entropy_coef: 0.01
  gamma: 0.99
  lam: 0.95
  max_grad_norm: 1.0
  normalize_advantage_per_mini_batch: false
  rnd_cfg: null
  symmetry_cfg: null
actor:
  class_name: MLPModel
  hidden_dims: [512, 256, 128]
  activation: elu
  obs_normalization: true
  distribution_cfg:
    class_name: GaussianDistribution
    init_std: 1.0
    std_type: scalar
critic:
  class_name: MLPModel
  hidden_dims: [512, 256, 128]
  activation: elu
  obs_normalization: true
